name: dhis2_dart_utils
description: A collection of data models, constants and utilities used to build a DHIS2 app in dart.
version: 1.1.9
homepage: https://github.com/hisptz/dhis2-dart-utils

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  dart_date: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
