name: dhis2_dart_utils
description: A collection of data models, constants and utilities used to build a DHIS2 app in dart.
version: 1.0.1
homepage: https://github.com/hisptz/dhis2-dart-utils

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_date: ^1.1.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
